#ifndef GUARD_CONSTANTS_BIOME_H
#define GUARD_CONSTANTS_BIOME_H

// Biome group IDs
#define BIOME_GROUP_NONE 0
#define BIOME_GROUP_OVERWORLD 1
#define BIOME_GROUP_CAVE 2
#define BIOME_GROUP_UNDERWATER 3
#define BIOME_GROUP_COUNT 4

// Biome IDs
#define BIOME_NONE 0
#define BIOME_SEASONAL 1
#define BIOME_TEMPERATE 2
#define BIOME_FOREST 3
#define BIOME_RAINFOREST 4
#define BIOME_TROPICAL 5
#define BIOME_DESERT 6
#define BIOME_TEMPERATE_ASH 7
#define BIOME_DESERT_ASH 8
#define BIOME_SAVANNA 9
#define BIOME_VOLCANIC 10
#define BIOME_COLD_FOREST 11
#define BIOME_TAIGA 12
#define BIOME_MOUNTAIN 13
#define BIOME_MOUNTAIN_PEAK 14
#define BIOME_CANYON 15
#define BIOME_CAVE 16
#define BIOME_CAVE_DRY 17
#define BIOME_CAVE_DAMP 18
#define BIOME_CAVE_MOSSY 19
#define BIOME_CAVE_SANDY 20
#define BIOME_UNDERWATER_SHALLOW 21
#define BIOME_UNDERWATER_DEEP 22
#define BIOME_UNDERWATER_ABYSS 23
#define BIOME_COUNT 24

// Relative IDs per biome group
#define BIOME_OW_NONE 0
#define BIOME_OW_SEASONAL 1
#define BIOME_OW_TEMPERATE 2
#define BIOME_OW_FOREST 3
#define BIOME_OW_RAINFOREST 4
#define BIOME_OW_TROPICAL 5
#define BIOME_OW_DESERT 6
#define BIOME_OW_TEMPERATE_ASH 7
#define BIOME_OW_DESERT_ASH 8
#define BIOME_OW_SAVANNA 9
#define BIOME_OW_VOLCANIC 10
#define BIOME_OW_COLD_FOREST 11
#define BIOME_OW_TAIGA 12
#define BIOME_OW_MOUNTAIN 13
#define BIOME_OW_MOUNTAIN_PEAK 14
#define BIOME_OW_CANYON 15
#define BIOME_OW_COUNT 16

#define BIOME_CV_NONE 0
#define BIOME_CV_CAVE 1
#define BIOME_CV_DRY 2
#define BIOME_CV_DAMP 3
#define BIOME_CV_MOSSY 4
#define BIOME_CV_SANDY 5
#define BIOME_CV_COUNT 6

#define BIOME_UW_NONE 0
#define BIOME_UW_SHALLOW 1
#define BIOME_UW_DEEP 2
#define BIOME_UW_ABYSS 3
#define BIOME_UW_COUNT 4

#endif